# Generated by Django 3.2.5 on 2021-07-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0002_auto_20210719_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to='post/'),
        ),
    ]
