# Generated by Django 3.2.5 on 2021-07-17 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Pin_Code',
            field=models.IntegerField(default=1000000, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='Profile_Image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
