# Generated by Django 3.2.5 on 2021-07-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0004_auto_20210719_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
