# Generated by Django 3.2.5 on 2021-07-17 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0004_auto_20210717_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Pin_Code',
            field=models.IntegerField(default=1000000, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(10000)]),
        ),
    ]
