# Generated by Django 3.2.5 on 2021-07-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0005_alter_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MH', 'Mental Health'), ('HD', 'Heart Disease'), ('CV', 'Covid19'), ('IM', 'Immunisation')], default=None, max_length=2),
        ),
    ]
