# Generated by Django 3.2.5 on 2021-07-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0007_alter_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_auth',
            field=models.JSONField(null=True),
        ),
    ]
